name: Keras Persistence Round-Trip

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install minimal dependencies
        run: |
          python -m pip install --upgrade pip
          pip install "tensorflow==2.20.0" "pytest>=8" "numpy>=2.3.0"
      - name: Run persistence round-trip test
        run: |
          pytest -q tests/test_keras_persistence_roundtrip.py
